<a href="https://colab.research.google.com/github/ishchuk/Deep_reinforcement_learning_Course/blob/master/FrozenLake_RL_QL_L2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from IPython.display import HTML
HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/q2ZOEFAaaI0?showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>')

In [0]:
import gym
import numpy as np
import random

In [0]:
env = gym.make("FrozenLake-v0")

In [0]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [6]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
total_episodes = 30000
learning_rate = 0.95
max_steps = 100
gamma = 0.95
epsilon = 1.0
max_epsilon=1.0
min_epsilon=0.01
decay_rate=0.015

In [0]:
from tqdm import tqdm

In [18]:
#list of rewards
rewards = []
for episode in tqdm(range(total_episodes)):
  #reset the env
  state = env.reset()
  step = 0
  done = False
  total_rewards = 0

  for steps in range(max_steps):
    #choose an action a in the current world state (s)
    #randomize for the first time
    exp_exp_tradeoff = random.uniform(0,1)

    #if this number > greater than epsilon --> explitation (taking the biggest Q value for this state)
    if exp_exp_tradeoff > epsilon:
      action = np.argmax(qtable[state,:])
      #else - doing a random choice > exploration
    else:
      action = env.action_space.sample()

    new_state, reward, done, info = env.step(action)
    qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :])- qtable[state, action])
    total_rewards += reward
    state = new_state
    if done == True:
      break
    
  epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
  rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

100%|██████████| 30000/30000 [00:32<00:00, 915.36it/s] 

Score over time: 0.44726666666666665
[[2.61067324e-01 1.92375872e-02 1.58051297e-02 2.37954073e-02]
 [2.83203474e-05 1.07819924e-03 6.32105878e-04 2.38608109e-02]
 [1.22796928e-04 9.71554261e-04 7.78618125e-03 8.47187800e-03]
 [7.19829723e-04 2.18295579e-03 5.54788949e-04 8.15939792e-03]
 [3.38377306e-01 1.53457262e-02 1.10656060e-02 2.62041148e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.30505797e-03 8.38788851e-22 3.69641198e-09 1.19769723e-08]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.20084563e-03 1.60319895e-02 8.48924321e-04 5.02881499e-01]
 [8.94326106e-05 6.50685275e-01 8.05295934e-06 1.62192586e-04]
 [1.83977882e-01 9.88248007e-05 2.51873736e-08 2.72251960e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.35709512e-02 2.33233444e-02 8.22307896e-01 4.05076320e-03]
 [7.48693532e-01 9.03672617e-01 7.37933556e-01 8.51597820e-02]
 [0.00000000e+00 0

In [19]:
env.reset()
for episode in range(5):
  state = env.reset()
  step = 0
  done = False
  print('*********************************************')
  print('EPISODE ', episode)

  for step in range(max_steps):
    action = np.argmax(qtable[state,:])
    new_state, reward, done, info = env.step(action)
    if done:
      env.render()
      print('Number Of Steps ', step)
      break

    state = new_state
env.close()

*********************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number Of Steps  25
*********************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number Of Steps  15
*********************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number Of Steps  23
*********************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number Of Steps  57
*********************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number Of Steps  76
